version: '3.7'

services:
  mongodb_container:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - 27017:27017
    restart: always
    logging:
      options:
        max-size: 1g
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
